services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
  backend:
    build: backend
    environment:
      TZ: 'Asia/Tokyo'
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE: test
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build: frontend
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - "80:80"
    depends_on:
      - backend